name: Update Mana Gauge

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  update-mana:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run mana script
        run: python .github/scripts/update_mana.py

      - name: Commit changes
        run: |
          git config --global user.name "Mana Bot"
          git config --global user.email "mana-bot@example.com"
          git add README.md
          git commit -m "🔁 Update Mana Gauge" || echo "No changes"
          git push --force
